language: python

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python: 3.6

sudo: false

install:
 - pip install flake8
 - pip install -r requirements.txt
 - npm install svgexport -g

script:
 # Fetch fresh copy of top packages
 - wget https://hugovk.github.io/top-pypi-packages/top-pypi-packages-365-days.min.json -O top-pypi-packages.json

 # Static analysis
 - flake8 --statistics --count .

 # Test run
 - python generate.py

matrix:
  fast_finish: true

notifications:
  email: false
